# Generated by Django 2.2.4 on 2019-08-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('no', models.IntegerField(db_column='dno', primary_key=True, serialize=False, verbose_name='部门编号')),
                ('name', models.CharField(db_column='dname', max_length=20, verbose_name='部门名称')),
                ('location', models.CharField(db_column='dloc', max_length=10, verbose_name='部门所在地')),
            ],
            options={
                'db_table': 'tb_dept',
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('no', models.IntegerField(db_column='eno', primary_key=True, serialize=False, verbose_name='员工编号')),
                ('name', models.CharField(db_column='ename', max_length=20, verbose_name='员工姓名')),
                ('job', models.CharField(max_length=10, verbose_name='职位')),
                ('sal', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='月薪')),
                ('comm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='补贴')),
                ('dept', models.ForeignKey(db_column='dno', on_delete=django.db.models.deletion.PROTECT, to='hrs.Dept', verbose_name='所在部门')),
                ('mgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrs.Emp', verbose_name='主管')),
            ],
            options={
                'db_table': 'tb_emp',
            },
        ),
    ]
